name: Test Deploy and Provision Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "pkg/deploy/**"
      - "pkg/provision/**"
      - "cmd/main.go"
      - "cmd/cmd/provision.go"
      - "cmd/cmd/provision_test.go"
      - "Makefile"
      - "roles_test_1/**"
      - "roles_test_2/**"
      - "runtimeassets.go"
      - ".github/workflows/test-cmd-unit-tests.yml"
      - ".github/workflows/test-deploy-unit-tests.yml"
  pull_request:
    paths:
      - "pkg/deploy/**"
      - "pkg/provision/**"
      - "cmd/main.go"
      - "cmd/cmd/provision.go"
      - "cmd/cmd/provision_test.go"
      - "Makefile"
      - "roles_test_1/**"
      - "roles_test_2/**"
      - "runtimeassets.go"
      - ".github/workflows/test-cmd-unit-tests.yml"
      - ".github/workflows/test-deploy-unit-tests.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Run deploy and provision unit tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Run deploy package tests
        run: go test -timeout 20m -v ./pkg/deploy/...

      - name: Run provision package tests
        run: go test -timeout 20m -v ./pkg/provision/...

      - name: Run cmd provision tests
        run: go test -timeout 20m -v ./cmd/cmd/...
